[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "20" }

# Handle API routes first (highest priority)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Netlify functions are handled automatically

# Exclude static assets from SPA redirect
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  force = false

# Handle specific SPA routes with proper client-side routing
[[redirects]]
  from = "/payment"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/payment/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/success"
  to = "/index.html"
  status = 200

# Catch-all for SPA routing (lowest priority)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[headers]]
  for = "/index.html"
    [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    # Ensure proper SPA behavior
    X-Robots-Tag = "noindex"

[[headers]]
  for = "/assets/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Improved CSP for Stripe integration and Supademo
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://js.stripe.com https://app.supademo.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https://*.stripe.com https://images.pexels.com https://fonts.gstatic.com https://tools.applemediaservices.com https://app.supademo.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://*.supabase.co https://api.stripe.com wss://*.supabase.co https://app.supademo.com; frame-src https://js.stripe.com https://hooks.stripe.com https://app.supademo.com; base-uri 'self'; form-action 'self' https://checkout.stripe.com; frame-ancestors 'none';"